version: '3'
services:
    mongo:
        image: mongo:3.2
        ports:
            - 27017:27017
        volumes:
            - ./charging-data:/data/db

    charging:
        image: charging-dev
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 8006:8006
        volumes:
            - ../src:/business-ecosystem-charging-backend/src/
